tags:
- name: users
  description: users API

paths:
# [GET] users
  /users:
    get:
      tags:
      - users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] users
    post:
      tags:
      - users
      summary: Add User
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] users/id
  /users/{id}:
    get:
      tags:
      - users
      summary: Find User By Id
      parameters:
      - name: id
        in: path
        description: User Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] users/id
    put:
      tags:
      - users
      summary: Update User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] users/id
    delete:
      tags:
      - users
      summary: Delete User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [POST] login
  /login:
    post:
      tags:
      - users
      summary: Login
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'


  # [POST] login
  /products:
    post:
      tags:
      - products
      summary: Add Category 
      parameters:
      - name: body
        in: body
        description: product Data
        required: true
        schema:
          $ref: '#/definitions/products'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
    get:
      tags:
      - products
      summary: Find All Products
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    put:
      tags:
      - products
      summary: Login
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/products'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
    delete:
      tags:
      - products
      summary: Login
      parameters:
      - name: body
        in: body
        description: product Data
        required: true
        schema:
          $ref: '#/definitions/products'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /categories:
    post:
      tags:
      - categories
      summary: Add Category 
      parameters:
      - name: body
        in: body
        description: category Data
        required: true
        schema:
          $ref: '#/definitions/categories'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
    get:
      tags:
      - categories
      summary: Find All Categorys
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    put:
      tags:
      - categories
      summary: Login
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/products'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
    delete:
      tags:
      - categories
      summary: Login
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/products'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
# definitions
  /products/getProductsByCategoryId:
    post: 
      tags:
      - products
      summary: Get Products By Category Id
      parameters:
      - name: body
        in: body
        description: category Data
        required: true
        schema:
            type: object
            properties:
              id:
                type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /carts:
    post:
      tags:
      - carts
      summary: Add Category 
      parameters:
      - name: body
        in: body
        description: product Data
        required: true
        schema:
          $ref: '#/definitions/cart'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
    get:
      tags:
      - carts
      summary: Find All Carts
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    put:
      tags:
      - carts
      summary: Edit Cart
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/cart'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
    delete:
      tags:
      - carts
      summary: Delete Cart
      parameters:
      - name: body
        in: body
        description: product Data
        required: true
        schema:
          $ref: '#/definitions/cart'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
definitions:
  users:
    type: object
    required:
        - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
      username:
        type: string
        description: user Username
  products:
    type: object
    required: false
    properties:
      price:
        type: number
        description: product Price
      category:
        type: string
        description: product category
      title:
        type: string
        description: product title
      description:
        type: string
        description: product description
      image:
        type: string
        description: product image
  categories:
    type: object
    required:
    properties:
      name:
        type: string
        description: category name
  cart:
    type: object
    required: false
    properties:
      user: 
        type: string
        description: user id
      product:
        type: string
        description: product Price
      quantity:
        type: number
        description: product category
      price:
        type: number
        description: product title
      description:
        type: string
        description: product description
      image:
        type: string
        description: product image
schemes:
 - https
 - http
